version: "3.8"
services:
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: database
    networks:
      - inet
    hostname: "adminer"
    ports:
      - 8080:8080
  database:
    image: postgres
    env_file:
      - "./database.env"
    networks:
      - inet
    hostname: "database"
    ports:
      - 5432:5432

networks:
  inet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
